-- Textures for eCastingBar
-- To add your own texture, just add the texture to the end of CASTINGBAR_TEXTURES_MENU in
-- the format { text = "Name", value = "Name" }, and then add the Name and Filepath to the end of 
-- CASTING_BAR_TEXTURES in the format ["Name"] = "Interface\\Addons\\eCastingBar\\Textures\\Texturename.tga"

CASTINGBAR_TEXTURES_MENU = {
		{ text = "Standard", value = "Standard"},
		{ text = "Perl", value = "Perl"},
		{ text = "Ace", value = "Ace"},
		{ text = "Banto", value = "Banto"},
		{ text = "Charcoal", value = "Charcoal"},
		{ text = "Classic", value = "Classic"},
		{ text = "Cool", value = "Cool"},
		{ text = "Elven", value = "Elven"},
		{ text = "Futuristic", value = "Futuristic"},
		{ text = "Futuristic_3D", value = "Futuristic_3D"},
		{ text = "Glaze", value = "Glaze"},
		{ text = "Gloss", value = "Gloss"},
		{ text = "Grunge", value = "Grunge"},
		{ text = "Halcyon", value = "Halcyon"},
		{ text = "Measurement", value = "Measurement"},
		{ text = "Metal", value = "Metal"},
		{ text = "Moonmaster", value = "Moonmaster"},
		{ text = "Smooth", value = "Smooth"},
		{ text = "Steel", value = "Steel"},
		{ text = "Stone", value = "Stone"},
		{ text = "Striped", value = "Striped"},
		{ text = "Water", value = "Water"},
};
CASTING_BAR_TEXTURES = {
	["Standard"] = "Interface\\TargetingFrame\\UI-StatusBar",
	["Perl"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Perl.tga",
	["Ace"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Ace.tga",
	["Banto"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Banto.tga",
	["Charcoal"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Charcoal.tga",
	["Classic"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Classic.tga",
	["Cool"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Cool.tga",
	["Elven"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Elven.tga",
	["Futuristic"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Futuristic.tga",
	["Futuristic_3D"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Futuristic_3d.tga",
	["Glaze"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Glaze.tga",
	["Gloss"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Gloss.tga",
	["Grunge"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Grunge.tga", 
	["Halcyon"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Halycon.tga",
	["Measurement"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Measurement.tga",
	["Metal"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Metal.tga", 
	["Moonmaster"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Moonmaster.tga",
	["Smooth"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Smooth.tga",
	["Steel"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Steel.tga", 
	["Stone"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Stone.tga", 
	["Striped"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Striped.tga", 
	["Water"] = "Interface\\AddOns\\eCastingBar\\Textures\\CastingBar_Water.tga", 
	};